[package]
name = "kissGraph3d"
version = "0.1.0"
authors = ["hoijui <hoijui.quaero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.24"
kiss3d = "0.29"

